name: Github CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install Codon + seq plugin
        run: |
          mkdir -p ${HOME}/.codon
          curl -L https://github.com/exaloop/codon/releases/download/v0.19.3/codon-linux-x86_64.tar.gz \
            | tar zxvf - --strip-components=1 -C ${HOME}/.codon
          curl -L https://github.com/exaloop/seq/releases/download/v0.11.5/seq-linux_x86_64.tar.gz \
            | tar zxvf - -C ${HOME}/.codon/lib/codon/plugins
          echo "${HOME}/.codon/bin" >> $GITHUB_PATH

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Set up Codon Python bridge
        run: |
          pip install -q find_libpython
          export CODON_PYTHON=$(find_libpython)
          echo "CODON_PYTHON=${CODON_PYTHON}" >> $GITHUB_ENV

      - name: Week 1 evaluate
        run: bash week1/evaluate.sh
        env:
          PY_ENTRY: "week1/codes/python/main.py"
          CODON_ENTRY: "week1/codes/codon/main_type.py"
          # CODON_ARGS_DEFAULT: "batch 25 100 0 1 3000 0 0 200000"

      - name: Upload results.csv
        uses: actions/upload-artifact@v4
        with:
          name: week1-results
          path: week1/results.csv

      - name: Upload contigs (if any)
        uses: actions/upload-artifact@v4
        with:
          name: contigs
          path: |
            week1/data/**/contigs.fasta
            week1/data/**/merged_contigs.fasta
          if-no-files-found: ignore
