name: Github CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install Codon + seq plugin
        run: |
          set -euxo pipefail
          CODON_HOME="${HOME}/.codon"
          mkdir -p "${CODON_HOME}/lib/codon/plugins"

          
          CODON_URL="https://github.com/exaloop/codon/releases/download/v0.19.3/codon-linux-x86_64.tar.gz"
          SEQ_URL="https://github.com/exaloop/seq/releases/download/v0.11.5/seq-linux-x86_64.tar.gz"

          # دانلود با fail-on-error
          curl -fL "$CODON_URL" -o /tmp/codon.tgz
          curl -fL "$SEQ_URL"   -o /tmp/seq.tgz

          # اکسترکت
          tar -xzf /tmp/codon.tgz -C "${CODON_HOME}" --strip-components=1
          tar -xzf /tmp/seq.tgz   -C "${CODON_HOME}/lib/codon/plugins"

          # در PATH بگذار
          echo "${CODON_HOME}/bin" >> "$GITHUB_PATH"

          # چاپ ساختار نصب برای دیباگ
          ls -R "${CODON_HOME}" | sed -n '1,120p'

          # تست نسخه
          "${CODON_HOME}/bin/codon" --version

          # smoke test برای seq plugin
          echo -ne "import bio\nprint('hello', s'ACGT')\n" | "${CODON_HOME}/bin/codon" run -plugin seq -

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Set up Codon Python bridge
        run: |
          set -euxo pipefail
          pip install -q find_libpython
          export CODON_PYTHON="$(find_libpython)"
          echo "CODON_PYTHON=${CODON_PYTHON}" >> "$GITHUB_ENV"

      - name: Week 1 evaluate
        run: bash week1/evaluate.sh
        env:
          # مسیرهای واقعی پروژهٔ تو (codes/)
          PY_ENTRY: "week1/codes/python/main.py"
          CODON_ENTRY: "week1/codes/codon/main_type.py"
          # پارامترهای سبک برای CI
          CODON_ARGS_DEFAULT: "batch 25 100 0 1 3000 0 0 200000"
          # اگر خواستی دیتاستی را حذف کنی (evaluate.sh فعلاً خودش فقط data1..3 را می‌خواند)
          # EXCLUDE_DATASETS: "data4"

      - name: Upload results.csv
        uses: actions/upload-artifact@v4
        with:
          name: week1-results
          path: week1/results.csv

      - name: Upload contigs (if any)
        uses: actions/upload-artifact@v4
        with:
          name: contigs
          path: |
            week1/data/**/contigs.fasta
            week1/data/**/merged_contigs.fasta
          if-no-files-found: ignore
      - name: Upload evaluator logs
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: week1/ci_logs/*.log
          if-no-files-found: ignore

